### ISSUE TITLE
Ablation studies that only using structure information

### ISSUE THREAD

**Issue by jianyucai** [StephanieWyt/RDGCN#5]
Hi,
Thanks for sharing your code.

I tried to conduct ablation studies that only uses the structure information. I made some modifications on the following function.

https://github.com/StephanieWyt/RDGCN/blob/d60ab1a82c367fb2156180f1679df8dc747242c8/include/Model.py#L187-L195

After modification, the entity embedding are not initialized from pretrained word embeddings. Instead, they are randomly initialized. However, ramdom initialization leads to significant decrement of the performance.

```python
def get_input_layer(e, dimension, lang):
    print('adding the primal input layer...')
    with open(file='data/' + lang + '_en/' + lang + '_vectorList.json', mode='r', encoding='utf-8') as f:
        embedding_list = json.load(f)
        print(len(embedding_list), 'rows,', len(embedding_list[0]), 'columns.')
    input_embeddings = tf.convert_to_tensor(embedding_list)
    # ent_embeddings = tf.Variable(input_embeddings)
    ent_embeddings = tf.Variable(tf.random.uniform(shape=tf.shape(input_embeddings)))
    return tf.nn.l2_normalize(ent_embeddings, 1)
```
On JA_EN dataset, H@1 only reaches 0.53% after 150/600 epochs.  Did I miss something? I would be grateful if you could reply to this issue. 

Thanks and regrads,

**Comment by StephanieWyt** [comment]
Hi,
Thanks for your interest in our work!

Based on the fact that our initial representations contain rich entity name information, we introduce highway gates in GCNs (Eq.10 and Eq. 11) and mix the initial representations with the output of primal attention layer (Eq. 8) to make full use of such useful information. Therefore, if you replace the entity name initialization with random initialization, it may be better to remove the above two designs. In addition, when using random initialization, I think it would be better to first use GCNs to pre-train entity embeddings on the primal graph and then add dual-primal interactions.

Best,
Yuting

**Comment by jianyucai** [comment]
Thanks for your reply.
