### ISSUE TITLE
当我在pycharm python3.5 tensorflow 1.10.0的环境下复现

### ISSUE THREAD

**Issue by HelloNman** [StephanieWyt/RDGCN#6]
出现了以下问题，请问您在运行代码时有这个问题吗？
Process finished with exit code -1073740791 (0xC0000409)

**Comment by StephanieWyt** [comment]
你好，感谢你对我们工作的关注！我们是在服务器上跑的代码，代码是可以正常运行的。

**Comment by HelloNman** [comment]
谢谢您的解答，刚才已经知道了是因为内存不足的原因


---原始邮件---
发件人: "Yuting Wu"<notifications@github.com&gt;
发送时间: 2020年6月23日(周二) 晚上11:04
收件人: "StephanieWyt/RDGCN"<RDGCN@noreply.github.com&gt;;
抄送: "HelloNman"<1506279945@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [StephanieWyt/RDGCN] 当我在pycharm python3.5 tensorflow 1.10.0的环境下复现 (#6)




 
你好，感谢你对我们工作的关注！我们是在服务器上跑的代码，代码是可以正常运行的。
